#inactivos:
#    path: /inactives.html
#    controller: App\Controller\ApartamentosController::inactive
#sinmapa:
#    path: /nomap.html
#    controller: App\Controller\ApartamentosController::nomap

#viewpublication:
#    path: /apto/{hash}
#    controller: App\Controller\ApartamentosController::apto

